image: registry.gitlab.isc.org/isc-projects/stork/ci-base:latest

# Only create pipelines for merge requests and pushes/merges to the main branch


# stages order

### build jobs ###

my_task:
  variables:
    FOO: BAR
  script:
    - echo $FOO

