linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  disable:
    - godox
    - maligned
    - lll
    - funlen
    - prealloc
    - wsl              # TODO: reenable later
    - interfacer       # A tool that suggests interfaces is prone to bad suggestions, so its usefulness in real code is limited.
    - dupl             # there are some false positives (identical code but operating on different types so no posibility to unify)
    - testpackage      # Requires rewriting a lot of unit tests and blocks the ability to test unexported functions.
    - wrapcheck        # We currently use pkg/errors tool that deals with the issue on its own.
    - exhaustivestruct # Most of the time you don't want to initialize all fields.
    - gomnd            # This may be useful but in many cases creating artificial constants, e.g. in tests is counter productive.
    - paralleltest     # This enforces t.Parallel() usage but some of our tests seem to work incorrectly. Need to fix it first.
    - nlreturn         # This seems to be overkill and sometimes new lines before continue or break is useless.
    - gci              # More less the same as goimports but it breaks imports grouping so it is not nice.

linters-settings:
  gocognit:
    min-complexity: 50
  nestif:
    min-complexity: 13
  exhaustive:
    # Treats switch statements with default case as taking into account all possible cases.
    # Without this setting the switch statements must enumerate all possible cases.
    default-signifies-exhaustive: true

issues:
  max-same-issues: 3

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst

    - linters:
        - gosec
      text: "G107"

    - linters:
        - gosec
      text: "G202"

    - path: api/gomock
      linters:
        - gochecknoglobals
        - wsl
        - gofmt
        - goimports

    - path: server/database/migrations/
      linters:
        - gochecknoinits
        - gochecknoglobals

    - path: version.go
      linters:
        - gochecknoglobals

    - path: server/database/settings.go
      linters:
        - gochecknoinits
